/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/64f1a714fe61576b46f27ca2.glb -o src/components/Avatar.jsx -k -r public
*/

import { useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import React, { useEffect, useRef, useState } from "react";
import * as THREE from "three";
import { getLipsyncManager } from "@/lib/lipsyncManager";

const facialExpressions = {
  default: {},
  smile: {
    browInnerUp: 0.17,
    eyeSquintLeft: 0.4,
    eyeSquintRight: 0.44,
    noseSneerLeft: 0.1700000727403593,
    noseSneerRight: 0.14000002836874015,
    mouthPressLeft: 0.61,
    mouthPressRight: 0.41000000000000003,
  },
  funnyFace: {
    jawLeft: 0.63,
    mouthPucker: 0.53,
    noseSneerLeft: 1,
    noseSneerRight: 0.39,
    mouthLeft: 1,
    eyeLookUpLeft: 1,
    eyeLookUpRight: 1,
    cheekPuff: 0.9999924982764238,
    mouthDimpleLeft: 0.414743888682652,
    mouthRollLower: 0.32,
    mouthSmileLeft: 0.35499733688813034,
    mouthSmileRight: 0.35499733688813034,
  },
  sad: {
    mouthFrownLeft: 1,
    mouthFrownRight: 1,
    mouthShrugLower: 0.78341,
    browInnerUp: 0.452,
    eyeSquintLeft: 0.72,
    eyeSquintRight: 0.75,
    eyeLookDownLeft: 0.5,
    eyeLookDownRight: 0.5,
    jawForward: 1,
  },
  surprised: {
    eyeWideLeft: 0.5,
    eyeWideRight: 0.5,
    jawOpen: 0.351,
    mouthFunnel: 1,
    browInnerUp: 1,
  },
  angry: {
    browDownLeft: 1,
    browDownRight: 1,
    eyeSquintLeft: 1,
    eyeSquintRight: 1,
    jawForward: 1,
    jawLeft: 1,
    mouthShrugLower: 1,
    noseSneerLeft: 1,
    noseSneerRight: 0.42,
    eyeLookDownLeft: 0.16,
    eyeLookDownRight: 0.16,
    cheekSquintLeft: 1,
    cheekSquintRight: 1,
    mouthClose: 0.23,
    mouthFunnel: 0.63,
    mouthDimpleRight: 1,
  },
  crazy: {
    browInnerUp: 0.9,
    jawForward: 1,
    noseSneerLeft: 0.5700000000000001,
    noseSneerRight: 0.51,
    eyeLookDownLeft: 0.39435766259644545,
    eyeLookUpRight: 0.4039761421719682,
    eyeLookInLeft: 0.9618479575523053,
    eyeLookInRight: 0.9618479575523053,
    jawOpen: 0.9618479575523053,
    mouthDimpleLeft: 0.9618479575523053,
    mouthDimpleRight: 0.9618479575523053,
    mouthStretchLeft: 0.27893590769016857,
    mouthStretchRight: 0.2885543872656917,
    mouthSmileLeft: 0.5578718153803371,
    mouthSmileRight: 0.38473918302092225,
    tongueOut: 0.9618479575523053,
  },
};

const corresponding = {
  A: "viseme_PP",
  B: "viseme_kk",
  C: "viseme_I",
  D: "viseme_AA",
  E: "viseme_O",
  F: "viseme_U",
  G: "viseme_FF",
  H: "viseme_TH",
  X: "viseme_PP",
};

let setupMode = false;

export function Avatar(props: any) {
  const { 
    animation: animationProp, 
    animations: animationsProp, 
    facialExpression: facialExpressionProp,
    audioElement, // Receive audio element from parent
    ...restProps 
  } = props;
  
  const { nodes, materials, scene } = useGLTF(
    "/models/Avatar.glb"
  ) as any;

  // Log available nodes to debug
  useEffect(() => {
    console.log("Available nodes:", Object.keys(nodes));
    console.log("Available materials:", Object.keys(materials));
    
    // Log viseme morph targets
    if (nodes.Wolf3D_Head && nodes.Wolf3D_Head.morphTargetDictionary) {
      const visemes = Object.keys(nodes.Wolf3D_Head.morphTargetDictionary).filter(key => 
        key.startsWith("viseme_")
      );
      console.log("👄 Available viseme morph targets:", visemes);
    }
    
    if (nodes.Wolf3D_Teeth && nodes.Wolf3D_Teeth.morphTargetDictionary) {
      const visemes = Object.keys(nodes.Wolf3D_Teeth.morphTargetDictionary).filter(key => 
        key.startsWith("viseme_")
      );
      console.log("🦷 Teeth viseme morph targets:", visemes);
    }
  }, [nodes, materials]);

  const [lipsync, setLipsync] = useState<any>();
  const lastVisemeRef = useRef<string>("");

  // Connect audio element to lipsync when it changes
  useEffect(() => {
    if (audioElement) {
      console.log("� Connecting audio element to lipsync manager");
      const lipsync = getLipsyncManager();
      lipsync.connectAudio(audioElement);
      console.log("✅ Audio connected successfully");
    }
  }, [audioElement]);

  // Use animations passed via props (from Experience component)
  const animations = animationsProp || [];

  const group = useRef<any>(null);
  const { actions } = useAnimations(animations, group);
  const [animation, setAnimation] = useState("Idle");

  useEffect(() => {
    console.log("Available animations:", animations.map((a: any) => a.name));
    console.log("Animation actions:", Object.keys(actions));
  }, [animations, actions]);

  // Update animation when prop changes
  useEffect(() => {
    if (animationProp) {
      console.log("Setting animation to:", animationProp);
      setAnimation(animationProp);
    }
  }, [animationProp]);

  useEffect(() => {
    if (!actions || Object.keys(actions).length === 0) {
      console.log("No actions available");
      return;
    }
    
    if (!animation) {
      console.log("No animation set");
      return;
    }
    
    console.log("Attempting to play animation:", animation);
    console.log("Available actions:", Object.keys(actions));
    
    const action = actions[animation];
    
    if (action) {
      console.log("✓ Playing animation:", animation);
      
      // Stop all other animations first
      Object.keys(actions).forEach(key => {
        if (key !== animation && actions[key]) {
          const otherAction = actions[key];
          if (otherAction.isRunning()) {
            otherAction.fadeOut(0.3);
          }
        }
      });
      
      // Configure and play the new animation
      action.reset();
      action.setLoop(THREE.LoopRepeat, Infinity); // Loop the animation
      action.clampWhenFinished = false;
      action.fadeIn(0.3);
      action.play();
      
      console.log("Animation started:", {
        name: animation,
        duration: action.getClip().duration,
        isRunning: action.isRunning()
      });
    } else {
      console.warn("❌ Animation not found:", animation);
    }
  }, [animation, actions]);

  const lerpMorphTarget = (target: string, value: number, speed = 0.1) => {
    scene.traverse((child: any) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = THREE.MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );

      }
    });
  };

  const [blink, setBlink] = useState(false);
  const [winkLeft, setWinkLeft] = useState(false);
  const [winkRight, setWinkRight] = useState(false);
  const [facialExpression, setFacialExpression] = useState("");

  // Update facial expression when prop changes
  useEffect(() => {
    if (facialExpressionProp !== undefined) {
      console.log("Setting facial expression to:", facialExpressionProp);
      setFacialExpression(facialExpressionProp);
    }
  }, [facialExpressionProp]);

  // Process lip sync in real-time
  useFrame(() => {
    // LIPSYNC - Process first before other morph targets
    if (audioElement) {
      const lipsync = getLipsyncManager();
      lipsync.processAudio();
      const currentViseme = lipsync.viseme;
      
      // Log viseme changes
      if (currentViseme && currentViseme !== lastVisemeRef.current) {
        console.log("👄 Viseme:", currentViseme);
        lastVisemeRef.current = currentViseme;
      }
      
      if (currentViseme) {
        // The library already returns the full viseme name (e.g., "viseme_E", "viseme_DD")
        // Apply the current viseme strongly
        lerpMorphTarget(currentViseme, 1, 0.5);
        
        // Get all viseme morph target names to reset others
        const allVisemes = new Set<string>();
        if (nodes.Wolf3D_Head?.morphTargetDictionary) {
          Object.keys(nodes.Wolf3D_Head.morphTargetDictionary).forEach(key => {
            if (key.startsWith("viseme_")) allVisemes.add(key);
          });
        }
        if (nodes.Wolf3D_Teeth?.morphTargetDictionary) {
          Object.keys(nodes.Wolf3D_Teeth.morphTargetDictionary).forEach(key => {
            if (key.startsWith("viseme_")) allVisemes.add(key);
          });
        }
        
        // Reset other visemes
        allVisemes.forEach((viseme) => {
          if (viseme !== currentViseme) {
            lerpMorphTarget(viseme, 0, 0.3);
          }
        });
      }
    } else {
      // Reset all visemes when not playing audio
      if (lastVisemeRef.current) {
        lastVisemeRef.current = "";
      }
      
      // Get all viseme morph target names to reset
      const allVisemes = new Set<string>();
      if (nodes.Wolf3D_Head?.morphTargetDictionary) {
        Object.keys(nodes.Wolf3D_Head.morphTargetDictionary).forEach(key => {
          if (key.startsWith("viseme_")) allVisemes.add(key);
        });
      }
      if (nodes.Wolf3D_Teeth?.morphTargetDictionary) {
        Object.keys(nodes.Wolf3D_Teeth.morphTargetDictionary).forEach(key => {
          if (key.startsWith("viseme_")) allVisemes.add(key);
        });
      }
      
      allVisemes.forEach((viseme) => {
        lerpMorphTarget(viseme, 0, 0.1);
      });
    }
    
    // FACIAL EXPRESSIONS - Process after lipsync
    if (!setupMode && nodes.EyeLeft && nodes.EyeLeft.morphTargetDictionary) {
      Object.keys(nodes.EyeLeft.morphTargetDictionary).forEach((key: string) => {
        const mapping = (facialExpressions as any)[facialExpression];
        
        // Skip blinking and visemes
        if (key === "eyeBlinkLeft" || key === "eyeBlinkRight" || key.startsWith("viseme_")) {
          return;
        }
        
        if (mapping && mapping[key]) {
          lerpMorphTarget(key, mapping[key], 0.1);
        } else {
          lerpMorphTarget(key, 0, 0.1);
        }
      });
    }

    lerpMorphTarget("eyeBlinkLeft", blink || winkLeft ? 1 : 0, 0.5);
    lerpMorphTarget("eyeBlinkRight", blink || winkRight ? 1 : 0, 0.5);
  });


  useEffect(() => {
    let blinkTimeout: NodeJS.Timeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 200);
      }, THREE.MathUtils.randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  return (
    <group {...restProps} dispose={null} ref={group} scale={1.4}>
      <primitive object={nodes.Hips} />
      {nodes.Wolf3D_Body && (
        <skinnedMesh
          name="Wolf3D_Body"
          geometry={nodes.Wolf3D_Body.geometry}
          material={materials.Wolf3D_Body}
          skeleton={nodes.Wolf3D_Body.skeleton}
        />
      )}
      {nodes.Wolf3D_Glasses && (
        <skinnedMesh
          name="Wolf3D_Glasses"
          geometry={nodes.Wolf3D_Glasses.geometry}
          material={materials.Wolf3D_Glasses}
          skeleton={nodes.Wolf3D_Glasses.skeleton}
        />
      )}
      {nodes.Wolf3D_Outfit_Bottom && (
        <skinnedMesh
          name="Wolf3D_Outfit_Bottom"
          geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
          material={materials.Wolf3D_Outfit_Bottom}
          skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
        />
      )}
      {nodes.Wolf3D_Outfit_Footwear && (
        <skinnedMesh
          name="Wolf3D_Outfit_Footwear"
          geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
          material={materials.Wolf3D_Outfit_Footwear}
          skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
        />
      )}
      {nodes.Wolf3D_Outfit_Top && (
        <skinnedMesh
          name="Wolf3D_Outfit_Top"
          geometry={nodes.Wolf3D_Outfit_Top.geometry}
          material={materials.Wolf3D_Outfit_Top}
          skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
        />
      )}
      {nodes.Wolf3D_Hair && (
        <skinnedMesh
          name="Wolf3D_Hair"
          geometry={nodes.Wolf3D_Hair.geometry}
          material={materials.Wolf3D_Hair}
          skeleton={nodes.Wolf3D_Hair.skeleton}
        />
      )}
      {nodes.EyeLeft && (
        <skinnedMesh
          name="EyeLeft"
          geometry={nodes.EyeLeft.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeLeft.skeleton}
          morphTargetDictionary={nodes.EyeLeft.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeLeft.morphTargetInfluences}
        />
      )}
      {nodes.EyeRight && (
        <skinnedMesh
          name="EyeRight"
          geometry={nodes.EyeRight.geometry}
          material={materials.Wolf3D_Eye}
          skeleton={nodes.EyeRight.skeleton}
          morphTargetDictionary={nodes.EyeRight.morphTargetDictionary}
          morphTargetInfluences={nodes.EyeRight.morphTargetInfluences}
        />
      )}
      {nodes.Wolf3D_Head && (
        <skinnedMesh
          name="Wolf3D_Head"
          geometry={nodes.Wolf3D_Head.geometry}
          material={materials.Wolf3D_Skin}
          skeleton={nodes.Wolf3D_Head.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Head.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Head.morphTargetInfluences}
        />
      )}
      {nodes.Wolf3D_Teeth && (
        <skinnedMesh
          name="Wolf3D_Teeth"
          geometry={nodes.Wolf3D_Teeth.geometry}
          material={materials.Wolf3D_Teeth}
          skeleton={nodes.Wolf3D_Teeth.skeleton}
          morphTargetDictionary={nodes.Wolf3D_Teeth.morphTargetDictionary}
          morphTargetInfluences={nodes.Wolf3D_Teeth.morphTargetInfluences}
        />
      )}
    </group>
  );
}

useGLTF.preload("/models/Avatar.glb");
